COLUMNS:
  abdominal_pain: int64
  abnormal_menstruation: int64
  acidity: int64
  acute_liver_failure: int64
  altered_sensorium: int64
  anxiety: int64
  back_pain: int64
  belly_pain: int64
  blackheads: int64
  bladder_discomfort: int64
  blister: int64
  blood_in_sputum: int64
  bloody_stool: int64
  blurred_and_distorted_vision: int64
  breathlessness: int64
  brittle_nails: int64
  bruising: int64
  burning_micturition: int64
  chest_pain: int64
  chills: int64
  cold_hands_and_feets: int64
  coma: int64
  congestion: int64
  constipation: int64
  continuous_feel_of_urine: int64
  continuous_sneezing: int64
  cough: int64
  cramps: int64
  dark_urine: int64
  dehydration: int64
  depression: int64
  diarrhoea: int64
  dischromic _patches: int64
  distention_of_abdomen: int64
  dizziness: int64
  drying_and_tingling_lips: int64
  enlarged_thyroid: int64
  excessive_hunger: int64
  extra_marital_contacts: int64
  family_history: int64
  fast_heart_rate: int64
  fatigue: int64
  fluid_overload: int64
  fluid_overload.1: int64
  foul_smell_of urine: int64
  headache: int64
  high_fever: int64
  hip_joint_pain: int64
  history_of_alcohol_consumption: int64
  increased_appetite: int64
  indigestion: int64
  inflammatory_nails: int64
  internal_itching: int64
  irregular_sugar_level: int64
  irritability: int64
  irritation_in_anus: int64
  itching: int64
  joint_pain: int64
  knee_pain: int64
  lack_of_concentration: int64
  lethargy: int64
  loss_of_appetite: int64
  loss_of_balance: int64
  loss_of_smell: int64
  malaise: int64
  mild_fever: int64
  mood_swings: int64
  movement_stiffness: int64
  mucoid_sputum: int64
  muscle_pain: int64
  muscle_wasting: int64
  muscle_weakness: int64
  nausea: int64
  neck_pain: int64
  nodal_skin_eruptions: int64
  obesity: int64
  pain_behind_the_eyes: int64
  pain_during_bowel_movements: int64
  pain_in_anal_region: int64
  painful_walking: int64
  palpitations: int64
  passage_of_gases: int64
  patches_in_throat: int64
  phlegm: int64
  polyuria: int64
  prognosis: object
  prominent_veins_on_calf: int64
  puffy_face_and_eyes: int64
  pus_filled_pimples: int64
  receiving_blood_transfusion: int64
  receiving_unsterile_injections: int64
  red_sore_around_nose: int64
  red_spots_over_body: int64
  redness_of_eyes: int64
  restlessness: int64
  runny_nose: int64
  rusty_sputum: int64
  scurring: int64
  shivering: int64
  silver_like_dusting: int64
  sinus_pressure: int64
  skin_peeling: int64
  skin_rash: int64
  slurred_speech: int64
  small_dents_in_nails: int64
  spinning_movements: int64
  spotting_ urination: int64
  stiff_neck: int64
  stomach_bleeding: int64
  stomach_pain: int64
  sunken_eyes: int64
  sweating: int64
  swelled_lymph_nodes: int64
  swelling_joints: int64
  swelling_of_stomach: int64
  swollen_blood_vessels: int64
  swollen_extremeties: int64
  swollen_legs: int64
  throat_irritation: int64
  toxic_look_(typhos): int64
  ulcers_on_tongue: int64
  unsteadiness: int64
  visual_disturbances: int64
  vomiting: int64
  watering_from_eyes: int64
  weakness_in_limbs: int64
  weakness_of_one_body_side: int64
  weight_gain: int64
  weight_loss: int64
  yellow_crust_ooze: int64
  yellow_urine: int64
  yellowing_of_eyes: int64
  yellowish_skin: int64


TARGET_COLUMN:
  name: prognosis