artifacts_root: artifacts

data_ingestion:

  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/vignesh2914/Datasets/main/Disease_prognosis.csv
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 